version: "3.1"

services:
  mongo:
    container_name: mongo
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: pwd
    ports:
      - 27017:27017
    volumes:
      - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongosh localhost:27017/test --quiet
      interval: 2s
      timeout: 2s
      retries: 5

  server:
    container_name: server
    build: ./server
    ports:
      - 3333:3333
    depends_on:
      mongo:
        condition: service_healthy

  app:
    container_name: app
    build: ./app
    ports:
      - 3000:3000
